name: libwinmedia
description: A cross-platform media playback library for C/C++ & Flutter with good number of features.
version: 0.0.7
homepage: https://github.com/harmonoid/libwinmedia
repository: https://github.com/harmonoid/libwinmedia

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  ffi: ^1.1.2
  path: ^1.8.0

dev_dependencies:
  ffigen: ^3.0.0

ffigen:
  output: 'lib/generated/bindings.dart'
  dart-bool: true
  headers:
    entry-points:
      - 'headers/main.h'
  name: 'LWM'
  description: 'Dart bindings to libwinmedia.'

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: LibwinmediaPlugin
      windows:
        pluginClass: LibwinmediaPlugin
